/*
 * SecuConnect API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.secuconnect.client.api;

import io.secuconnect.client.ApiException;
import io.secuconnect.client.model.PaymentCustomersDTO;
import io.secuconnect.client.model.PaymentCustomersList;
import io.secuconnect.client.model.PaymentCustomersProductModel;
import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for PaymentCustomersApi
 */
@Ignore
public class PaymentCustomersApiTest {

    private final PaymentCustomersApi api = new PaymentCustomersApi();

    
    /**
     * 
     *
     * Get a list of payment customers
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentCustomersGetTest() throws ApiException {
        Integer count = null;
        Integer offset = null;
        String fields = null;
        String q = null;
        String sort = null;
        PaymentCustomersList response = api.paymentCustomersGet(count, offset, fields, q, sort);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get all payment customers
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentCustomersGetByIdTest() throws ApiException {
        String id = null;
        PaymentCustomersProductModel response = api.paymentCustomersGetById(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Delete payment customer
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentCustomersIdDeleteTest() throws ApiException {
        String id = null;
        List<PaymentCustomersProductModel> response = api.paymentCustomersIdDelete(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Update payment customer
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentCustomersIdPutTest() throws ApiException {
        String id = null;
        PaymentCustomersDTO body = null;
        PaymentCustomersProductModel response = api.paymentCustomersIdPut(id, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Add new customer
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentCustomersPostTest() throws ApiException {
        PaymentCustomersDTO body = null;
        PaymentCustomersProductModel response = api.paymentCustomersPost(body);

        // TODO: test validations
    }
    
}
