/*
 * SecuConnect API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.secuconnect.client.api;

import com.secuconnect.client.ApiException;
import com.secuconnect.client.model.PaymentTransactionCancelDTO;
import com.secuconnect.client.model.PaymentTransactionsList;
import com.secuconnect.client.model.PaymentTransactionsProductModel;
import com.secuconnect.client.model.PaymentTransactionsShippingUrl;
import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for PaymentTransactionsApi
 */
@Ignore
public class PaymentTransactionsApiTest {

    private final PaymentTransactionsApi api = new PaymentTransactionsApi();

    
    /**
     * 
     *
     * Get a list of payment transactions
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentTransactionsGetTest() throws ApiException {
        Integer count = null;
        Integer offset = null;
        String fields = null;
        String q = null;
        String sort = null;
        PaymentTransactionsList response = api.getAll(count, offset, fields, q, sort);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get all payment transactions
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentTransactionsGetByIdTest() throws ApiException {
        String id = null;
        PaymentTransactionsProductModel response = api.getOne(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Cancel a payment transaction
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentTransactionsIdCancelPostTest() throws ApiException {
        String id = null;
        PaymentTransactionCancelDTO body = new PaymentTransactionCancelDTO();
        List<PaymentTransactionsProductModel> response = api.cancel(id, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get the url where you can fill the shipping information
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentTransactionsIdShippingUrlGetTest() throws ApiException {
        String id = null;
        PaymentTransactionsShippingUrl response = api.getShippingUrl(id);

        // TODO: test validations
    }
    
}
