/*
 * SecuConnect API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.secuconnect.client.api;

import com.secuconnect.client.ApiException;
import com.secuconnect.client.model.ProductExceptionPayload;
import com.secuconnect.client.model.SecupayTransactionProductDTO;
import com.secuconnect.client.model.SecupayTransactionProductModel;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentSecupayCreditcardsApi
 */
@Ignore
public class PaymentSecupayCreditcardsApiTest {

    private final PaymentSecupayCreditcardsApi api = new PaymentSecupayCreditcardsApi();

    
    /**
     * 
     *
     * Function to cancel the transaction
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentSecupayCreditcardsCancelByIdTest() throws ApiException {
        String hash = null;
        Object response = api.paymentSecupayCreditcardsCancelById(hash);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get the details of a payment transaction
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentSecupayCreditcardsGetByIdTest() throws ApiException {
        String hash = null;
        SecupayTransactionProductModel response = api.paymentSecupayCreditcardsGetById(hash);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Start a credit card payment transaction
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentSecupaycreditcardsPostTest() throws ApiException {
        SecupayTransactionProductDTO body = null;
        SecupayTransactionProductModel response = api.paymentSecupaycreditcardsPost(body);

        // TODO: test validations
    }
    
}
