/*
 * SecuConnect API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.secuconnect.client.api;

import io.secuconnect.client.ApiException;
import io.secuconnect.client.model.PaymentContractsDTO;
import io.secuconnect.client.model.PaymentContractsList;
import io.secuconnect.client.model.PaymentContractsProductModel;
import io.secuconnect.client.model.PaymentContractsRequestIdResult;
import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for PaymentContractsApi
 */
@Ignore
public class PaymentContractsApiTest {

    private final PaymentContractsApi api = new PaymentContractsApi();

    
    /**
     * 
     *
     * Get a list of payment contracts
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentContractsGetTest() throws ApiException {
        Integer count = null;
        Integer offset = null;
        String fields = null;
        String q = null;
        String sort = null;
        PaymentContractsList response = api.paymentContractsGet(count, offset, fields, q, sort);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get all payment contracts
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentContractsGetByIdTest() throws ApiException {
        String id = null;
        PaymentContractsProductModel response = api.paymentContractsGetById(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Clone an existing payment contract
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentContractsIdClonePostTest() throws ApiException {
        String id = null;
        PaymentContractsProductModel response = api.paymentContractsIdClonePost(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Delete payment contract
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentContractsIdDeleteTest() throws ApiException {
        String id = null;
        List<PaymentContractsProductModel> response = api.paymentContractsIdDelete(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get available payment methods for given contract
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentContractsIdPaymentMethodsGetTest() throws ApiException {
        String id = null;
        List<String> response = api.paymentContractsIdPaymentMethodsGet(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Update payment contract
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentContractsIdPutTest() throws ApiException {
        String id = null;
        PaymentContractsDTO body = null;
        PaymentContractsProductModel response = api.paymentContractsIdPut(id, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * This method clones your payment contract, so that you can use this to separate the merchants of your marketplace. (Needs to be activated))
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentContractsIdRequestIdPostTest() throws ApiException {
        String id = null;
        PaymentContractsRequestIdResult response = api.paymentContractsIdRequestIdPost(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Add new contract
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentContractsPostTest() throws ApiException {
        PaymentContractsDTO body = null;
        PaymentContractsProductModel response = api.paymentContractsPost(body);

        // TODO: test validations
    }
    
}
