/*
 * SecuConnect API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.secuconnect.client.api;

import io.secuconnect.client.ApiException;
import io.secuconnect.client.model.ProductExceptionPayload;
import io.secuconnect.client.model.SecupayTransactionProductDTO;
import io.secuconnect.client.model.SecupayTransactionProductModel;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentSecupayInvoicesApi
 */
@Ignore
public class PaymentSecupayInvoicesApiTest {

    private final PaymentSecupayInvoicesApi api = new PaymentSecupayInvoicesApi();

    
    /**
     * 
     *
     * Function to cancel the transaction
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentSecupayInvoicesCancelByIdTest() throws ApiException {
        String hash = null;
        Object response = api.paymentSecupayInvoicesCancelById(hash);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get the details of a payment transaction
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentSecupayInvoicesGetByIdTest() throws ApiException {
        String hash = null;
        SecupayTransactionProductModel response = api.paymentSecupayInvoicesGetById(hash);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Start a invoice payment transaction
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentSecupayinvoicesPostTest() throws ApiException {
        SecupayTransactionProductDTO body = null;
        SecupayTransactionProductModel response = api.paymentSecupayinvoicesPost(body);

        // TODO: test validations
    }
    
}
