/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.secuconnect.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.secuconnect.client.model.PaymentContainersProductModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PaymentContainersList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-16T14:16:54.610+02:00")
public class PaymentContainersList {
  @SerializedName("count")
  private Integer count = null;

  @SerializedName("data")
  private List<PaymentContainersProductModel> data = null;

  public PaymentContainersList count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Number of existing payment containers
   * @return count
  **/
  @ApiModelProperty(value = "Number of existing payment containers")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public PaymentContainersList data(List<PaymentContainersProductModel> data) {
    this.data = data;
    return this;
  }

  public PaymentContainersList addDataItem(PaymentContainersProductModel dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<PaymentContainersProductModel>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * GET Payment/Containers
   * @return data
  **/
  @ApiModelProperty(value = "GET Payment/Containers")
  public List<PaymentContainersProductModel> getData() {
    return data;
  }

  public void setData(List<PaymentContainersProductModel> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentContainersList paymentContainersList = (PaymentContainersList) o;
    return Objects.equals(this.count, paymentContainersList.count) &&
        Objects.equals(this.data, paymentContainersList.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentContainersList {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

