/*
 * SecuConnect API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.secuconnect.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.secuconnect.client.model.Address;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PaymentCustomersDTOContact
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-16T16:36:34.187+02:00")
public class PaymentCustomersDTOContact {
  @SerializedName("forename")
  private String forename = null;

  @SerializedName("surname")
  private String surname = null;

  @SerializedName("companyname")
  private String companyname = null;

  @SerializedName("salutation")
  private String salutation = null;

  @SerializedName("gender")
  private String gender = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("phone")
  private String phone = null;

  @SerializedName("mobile")
  private String mobile = null;

  @SerializedName("dob")
  private String dob = null;

  @SerializedName("picture")
  private String picture = null;

  @SerializedName("url_website")
  private String urlWebsite = null;

  @SerializedName("birthplace")
  private String birthplace = null;

  @SerializedName("nationality")
  private String nationality = null;

  @SerializedName("address")
  private Address address = null;

  public PaymentCustomersDTOContact forename(String forename) {
    this.forename = forename;
    return this;
  }

   /**
   * Customer forename
   * @return forename
  **/
  @ApiModelProperty(value = "Customer forename")
  public String getForename() {
    return forename;
  }

  public void setForename(String forename) {
    this.forename = forename;
  }

  public PaymentCustomersDTOContact surname(String surname) {
    this.surname = surname;
    return this;
  }

   /**
   * Customer surname
   * @return surname
  **/
  @ApiModelProperty(value = "Customer surname")
  public String getSurname() {
    return surname;
  }

  public void setSurname(String surname) {
    this.surname = surname;
  }

  public PaymentCustomersDTOContact companyname(String companyname) {
    this.companyname = companyname;
    return this;
  }

   /**
   * Customer company name
   * @return companyname
  **/
  @ApiModelProperty(value = "Customer company name")
  public String getCompanyname() {
    return companyname;
  }

  public void setCompanyname(String companyname) {
    this.companyname = companyname;
  }

  public PaymentCustomersDTOContact salutation(String salutation) {
    this.salutation = salutation;
    return this;
  }

   /**
   * Customer salutation
   * @return salutation
  **/
  @ApiModelProperty(value = "Customer salutation")
  public String getSalutation() {
    return salutation;
  }

  public void setSalutation(String salutation) {
    this.salutation = salutation;
  }

  public PaymentCustomersDTOContact gender(String gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Customer gender
   * @return gender
  **/
  @ApiModelProperty(value = "Customer gender")
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public PaymentCustomersDTOContact title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Customer title
   * @return title
  **/
  @ApiModelProperty(value = "Customer title")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public PaymentCustomersDTOContact email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Customer email
   * @return email
  **/
  @ApiModelProperty(value = "Customer email")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public PaymentCustomersDTOContact phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Customer phone
   * @return phone
  **/
  @ApiModelProperty(value = "Customer phone")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public PaymentCustomersDTOContact mobile(String mobile) {
    this.mobile = mobile;
    return this;
  }

   /**
   * Customer mobile
   * @return mobile
  **/
  @ApiModelProperty(value = "Customer mobile")
  public String getMobile() {
    return mobile;
  }

  public void setMobile(String mobile) {
    this.mobile = mobile;
  }

  public PaymentCustomersDTOContact dob(String dob) {
    this.dob = dob;
    return this;
  }

   /**
   * Date of birth &#39;/^\\d{4}-\\d{2}-\\d{2}(T\\d{2}:\\d{2}:\\d{2}[+-]\\d{2}:\\d{2})?$/i&#39;
   * @return dob
  **/
  @ApiModelProperty(value = "Date of birth '/^\\d{4}-\\d{2}-\\d{2}(T\\d{2}:\\d{2}:\\d{2}[+-]\\d{2}:\\d{2})?$/i'")
  public String getDob() {
    return dob;
  }

  public void setDob(String dob) {
    this.dob = dob;
  }

  public PaymentCustomersDTOContact picture(String picture) {
    this.picture = picture;
    return this;
  }

   /**
   * The document id of an user picture (To upload the picture use our document service.)
   * @return picture
  **/
  @ApiModelProperty(value = "The document id of an user picture (To upload the picture use our document service.)")
  public String getPicture() {
    return picture;
  }

  public void setPicture(String picture) {
    this.picture = picture;
  }

  public PaymentCustomersDTOContact urlWebsite(String urlWebsite) {
    this.urlWebsite = urlWebsite;
    return this;
  }

   /**
   * URL to customer website
   * @return urlWebsite
  **/
  @ApiModelProperty(value = "URL to customer website")
  public String getUrlWebsite() {
    return urlWebsite;
  }

  public void setUrlWebsite(String urlWebsite) {
    this.urlWebsite = urlWebsite;
  }

  public PaymentCustomersDTOContact birthplace(String birthplace) {
    this.birthplace = birthplace;
    return this;
  }

   /**
   * Customer birthplace
   * @return birthplace
  **/
  @ApiModelProperty(value = "Customer birthplace")
  public String getBirthplace() {
    return birthplace;
  }

  public void setBirthplace(String birthplace) {
    this.birthplace = birthplace;
  }

  public PaymentCustomersDTOContact nationality(String nationality) {
    this.nationality = nationality;
    return this;
  }

   /**
   * Customer nationality
   * @return nationality
  **/
  @ApiModelProperty(value = "Customer nationality")
  public String getNationality() {
    return nationality;
  }

  public void setNationality(String nationality) {
    this.nationality = nationality;
  }

  public PaymentCustomersDTOContact address(Address address) {
    this.address = address;
    return this;
  }

   /**
   * Customer address
   * @return address
  **/
  @ApiModelProperty(value = "Customer address")
  public Address getAddress() {
    return address;
  }

  public void setAddress(Address address) {
    this.address = address;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentCustomersDTOContact paymentCustomersDTOContact = (PaymentCustomersDTOContact) o;
    return Objects.equals(this.forename, paymentCustomersDTOContact.forename) &&
        Objects.equals(this.surname, paymentCustomersDTOContact.surname) &&
        Objects.equals(this.companyname, paymentCustomersDTOContact.companyname) &&
        Objects.equals(this.salutation, paymentCustomersDTOContact.salutation) &&
        Objects.equals(this.gender, paymentCustomersDTOContact.gender) &&
        Objects.equals(this.title, paymentCustomersDTOContact.title) &&
        Objects.equals(this.email, paymentCustomersDTOContact.email) &&
        Objects.equals(this.phone, paymentCustomersDTOContact.phone) &&
        Objects.equals(this.mobile, paymentCustomersDTOContact.mobile) &&
        Objects.equals(this.dob, paymentCustomersDTOContact.dob) &&
        Objects.equals(this.picture, paymentCustomersDTOContact.picture) &&
        Objects.equals(this.urlWebsite, paymentCustomersDTOContact.urlWebsite) &&
        Objects.equals(this.birthplace, paymentCustomersDTOContact.birthplace) &&
        Objects.equals(this.nationality, paymentCustomersDTOContact.nationality) &&
        Objects.equals(this.address, paymentCustomersDTOContact.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(forename, surname, companyname, salutation, gender, title, email, phone, mobile, dob, picture, urlWebsite, birthplace, nationality, address);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentCustomersDTOContact {\n");
    
    sb.append("    forename: ").append(toIndentedString(forename)).append("\n");
    sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
    sb.append("    companyname: ").append(toIndentedString(companyname)).append("\n");
    sb.append("    salutation: ").append(toIndentedString(salutation)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    mobile: ").append(toIndentedString(mobile)).append("\n");
    sb.append("    dob: ").append(toIndentedString(dob)).append("\n");
    sb.append("    picture: ").append(toIndentedString(picture)).append("\n");
    sb.append("    urlWebsite: ").append(toIndentedString(urlWebsite)).append("\n");
    sb.append("    birthplace: ").append(toIndentedString(birthplace)).append("\n");
    sb.append("    nationality: ").append(toIndentedString(nationality)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

