/*
 * SecuConnect API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.secuconnect.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PaymentContainerMandate
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-16T14:16:54.610+02:00")
public class PaymentContainerMandate {
  @SerializedName("sepa_mandate_id")
  private String sepaMandateId = null;

  @SerializedName("iban")
  private String iban = null;

  @SerializedName("bic")
  private String bic = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("identification")
  private String identification = null;

  public PaymentContainerMandate sepaMandateId(String sepaMandateId) {
    this.sepaMandateId = sepaMandateId;
    return this;
  }

   /**
   * Sepa mandate id
   * @return sepaMandateId
  **/
  @ApiModelProperty(value = "Sepa mandate id")
  public String getSepaMandateId() {
    return sepaMandateId;
  }

  public void setSepaMandateId(String sepaMandateId) {
    this.sepaMandateId = sepaMandateId;
  }

  public PaymentContainerMandate iban(String iban) {
    this.iban = iban;
    return this;
  }

   /**
   * IBAN
   * @return iban
  **/
  @ApiModelProperty(value = "IBAN")
  public String getIban() {
    return iban;
  }

  public void setIban(String iban) {
    this.iban = iban;
  }

  public PaymentContainerMandate bic(String bic) {
    this.bic = bic;
    return this;
  }

   /**
   * BIC
   * @return bic
  **/
  @ApiModelProperty(value = "BIC")
  public String getBic() {
    return bic;
  }

  public void setBic(String bic) {
    this.bic = bic;
  }

  public PaymentContainerMandate type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type
   * @return type
  **/
  @ApiModelProperty(value = "Type")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public PaymentContainerMandate status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status
   * @return status
  **/
  @ApiModelProperty(value = "Status")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public PaymentContainerMandate identification(String identification) {
    this.identification = identification;
    return this;
  }

   /**
   * Identification
   * @return identification
  **/
  @ApiModelProperty(value = "Identification")
  public String getIdentification() {
    return identification;
  }

  public void setIdentification(String identification) {
    this.identification = identification;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentContainerMandate paymentContainerMandate = (PaymentContainerMandate) o;
    return Objects.equals(this.sepaMandateId, paymentContainerMandate.sepaMandateId) &&
        Objects.equals(this.iban, paymentContainerMandate.iban) &&
        Objects.equals(this.bic, paymentContainerMandate.bic) &&
        Objects.equals(this.type, paymentContainerMandate.type) &&
        Objects.equals(this.status, paymentContainerMandate.status) &&
        Objects.equals(this.identification, paymentContainerMandate.identification);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sepaMandateId, iban, bic, type, status, identification);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentContainerMandate {\n");
    
    sb.append("    sepaMandateId: ").append(toIndentedString(sepaMandateId)).append("\n");
    sb.append("    iban: ").append(toIndentedString(iban)).append("\n");
    sb.append("    bic: ").append(toIndentedString(bic)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    identification: ").append(toIndentedString(identification)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

